# compose bueno ya funciona

version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sds2025_blog_app
    ports:
      - "8081:80"
    volumes:
      - "./blog_MVC/public:/var/www/html:cached"
      - "./blog_MVC/app:/var/www/app:cached"
      - "./blog_MVC/lib:/var/www/lib:cached"
      - "./blog_MVC/routes:/var/www/routes:cached"
      - "./blog_MVC/autoloader.php:/var/www/autoloader.php:cached"
      - "./conexionBD:/var/www/conexionBD:cached"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: sds2025_blog_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: blog_sds2025 
      TZ: America/El_Salvador
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sds2025_blog_phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "8082:80"

volumes:
  db_data:
