services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php82-apache
    ports:
      - "8080:80"
    volumes:
      - ./blog_MVC/public:/var/www/html
      - ./blog_MVC/app:/var/www/app
      - ./blog_MVC/lib:/var/www/lib
      - ./blog_MVC/routes:/var/www/routes
      - ./blog_MVC/autoloader.php:/var/www/autoloader.php
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql80
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -prootpass || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8082:80"

volumes:
  db_data:
